/**
 * dbconfigTest.java
 *
 * This file was generated by XMLSpy 2006r3sp1 Enterprise Edition.
 *
 * YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
 * OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
 *
 * Refer to the XMLSpy Documentation for further details.
 * http://www.altova.com/xmlspy
 */


package com.dbconfigTest;

import com.altova.*;
import com.altova.types.*;
import com.dbconfig.*;

public class dbconfigTest {
	protected static void example() throws Exception {
		////////////////////////////////////////////////////////////////////
		//
		// TODO:
		//   Insert your code here...
		//
		// Example code to create and save a structure:
		//   dbconfigDoc doc = new dbconfigDoc();
		//   dbconfigType root = new dbconfigType(doc, "", "", "dbconfig");
		//   doc.setSchemaLocation("dbconfig.xsd"); // optional
		//   ...
		//   doc.save("dbconfig1.xml", root);
		//
		// Example code to load and save a structure:
		//   dbconfigDoc doc = new dbconfigDoc();
		//   dbconfigType root = new dbconfigType(doc.load("dbconfig1.xml"));
		//   ...
		//   doc.save("dbconfig1.xml", root);
		//
		////////////////////////////////////////////////////////////////////
	}

	public static void main(String args[]) {
		try {
			System.out.println("dbconfig Test Application");
			example();
			System.out.println("OK");
			System.exit(0);
		} catch (Exception e) {
			e.printStackTrace();
			System.exit(1);
		}
	}
}
