/**
 * columnType.java
 *
 * This file was generated by XMLSpy 2006r3sp1 Enterprise Edition.
 *
 * YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
 * OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
 *
 * Refer to the XMLSpy Documentation for further details.
 * http://www.altova.com/xmlspy
 */


package com.dbconfig;

import com.altova.types.*;

public class columnType extends com.altova.xml.Node {

	public columnType(columnType node) {
		super(node);
	}

	public columnType(org.w3c.dom.Node node) {
		super(node);
	}

	public columnType(org.w3c.dom.Document doc) {
		super(doc);
	}

	public columnType(com.altova.xml.Document doc, String namespaceURI, String prefix, String name) {
		super(doc, namespaceURI, prefix, name);
	}
	
	public void adjustPrefix() {
		for (	org.w3c.dom.Node tmpNode = getDomFirstChild( Element, null, "colURI" );
				tmpNode != null;
				tmpNode = getDomNextChild( Element, null, "colURI", tmpNode )
			) {
			internalAdjustPrefix(tmpNode, true);
		}
		for (	org.w3c.dom.Node tmpNode = getDomFirstChild( Element, null, "filePath" );
				tmpNode != null;
				tmpNode = getDomNextChild( Element, null, "filePath", tmpNode )
			) {
			internalAdjustPrefix(tmpNode, true);
		}
		for (	org.w3c.dom.Node tmpNode = getDomFirstChild( Element, null, "dataType" );
				tmpNode != null;
				tmpNode = getDomNextChild( Element, null, "dataType", tmpNode )
			) {
			internalAdjustPrefix(tmpNode, true);
		}
	}

	public static int getcolURIMinCount() {
		return 1;
	}

	public static int getcolURIMaxCount() {
		return 1;
	}

	public int getcolURICount() {
		return getDomChildCount(Element, null, "colURI");
	}

	public boolean hascolURI() {
		return hasDomChild(Element, null, "colURI");
	}

	public com.altova.xml.AnyTypeNode newcolURI() {
		return new com.altova.xml.AnyTypeNode(domNode.getOwnerDocument().createElementNS(null, "colURI"));
	}

	public com.altova.xml.AnyTypeNode getcolURIAt(int index) throws Exception {
		return new com.altova.xml.AnyTypeNode(dereference(getDomChildAt(Element, null, "colURI", index)));
	}

	public org.w3c.dom.Node getStartingcolURICursor() throws Exception {
		return getDomFirstChild(Element, null, "colURI" );
	}

	public org.w3c.dom.Node getAdvancedcolURICursor( org.w3c.dom.Node curNode ) throws Exception {
		return getDomNextChild( Element, null, "colURI", curNode );
	}

	public com.altova.xml.AnyTypeNode getcolURIValueAtCursor( org.w3c.dom.Node curNode ) throws Exception {
		if( curNode == null )
			throw new com.altova.xml.XmlException("Out of range");
		else
			return new com.altova.xml.AnyTypeNode( dereference(curNode) );
	}

	public com.altova.xml.AnyTypeNode getcolURI() throws Exception 
 {
		return getcolURIAt(0);
	}

	public void removecolURIAt(int index) {
		removeDomChildAt(Element, null, "colURI", index);
	}

	public void removecolURI() {
		removecolURIAt(0);
	}

	public void addcolURI(com.altova.xml.AnyTypeNode value) {
		appendDomElement(null, "colURI", value);	
	}

	public void insertcolURIAt(com.altova.xml.AnyTypeNode value, int index) {
		insertDomElementAt(null, "colURI", index, value);
	}

	public void replacecolURIAt(com.altova.xml.AnyTypeNode value, int index) {
		replaceDomElementAt(null, "colURI", index, value);
	}

	public static int getfilePathMinCount() {
		return 1;
	}

	public static int getfilePathMaxCount() {
		return 1;
	}

	public int getfilePathCount() {
		return getDomChildCount(Element, null, "filePath");
	}

	public boolean hasfilePath() {
		return hasDomChild(Element, null, "filePath");
	}

	public com.altova.xml.AnyTypeNode newfilePath() {
		return new com.altova.xml.AnyTypeNode(domNode.getOwnerDocument().createElementNS(null, "filePath"));
	}

	public com.altova.xml.AnyTypeNode getfilePathAt(int index) throws Exception {
		return new com.altova.xml.AnyTypeNode(dereference(getDomChildAt(Element, null, "filePath", index)));
	}

	public org.w3c.dom.Node getStartingfilePathCursor() throws Exception {
		return getDomFirstChild(Element, null, "filePath" );
	}

	public org.w3c.dom.Node getAdvancedfilePathCursor( org.w3c.dom.Node curNode ) throws Exception {
		return getDomNextChild( Element, null, "filePath", curNode );
	}

	public com.altova.xml.AnyTypeNode getfilePathValueAtCursor( org.w3c.dom.Node curNode ) throws Exception {
		if( curNode == null )
			throw new com.altova.xml.XmlException("Out of range");
		else
			return new com.altova.xml.AnyTypeNode( dereference(curNode) );
	}

	public com.altova.xml.AnyTypeNode getfilePath() throws Exception 
 {
		return getfilePathAt(0);
	}

	public void removefilePathAt(int index) {
		removeDomChildAt(Element, null, "filePath", index);
	}

	public void removefilePath() {
		removefilePathAt(0);
	}

	public void addfilePath(com.altova.xml.AnyTypeNode value) {
		appendDomElement(null, "filePath", value);	
	}

	public void insertfilePathAt(com.altova.xml.AnyTypeNode value, int index) {
		insertDomElementAt(null, "filePath", index, value);
	}

	public void replacefilePathAt(com.altova.xml.AnyTypeNode value, int index) {
		replaceDomElementAt(null, "filePath", index, value);
	}

	public static int getdataTypeMinCount() {
		return 1;
	}

	public static int getdataTypeMaxCount() {
		return 1;
	}

	public int getdataTypeCount() {
		return getDomChildCount(Element, null, "dataType");
	}

	public boolean hasdataType() {
		return hasDomChild(Element, null, "dataType");
	}

	public dataTypeType newdataType() {
		return new dataTypeType();
	}

	public dataTypeType getdataTypeAt(int index) throws Exception {
		return new dataTypeType(getDomNodeValue(dereference(getDomChildAt(Element, null, "dataType", index))));
	}

	public org.w3c.dom.Node getStartingdataTypeCursor() throws Exception {
		return getDomFirstChild(Element, null, "dataType" );
	}

	public org.w3c.dom.Node getAdvanceddataTypeCursor( org.w3c.dom.Node curNode ) throws Exception {
		return getDomNextChild( Element, null, "dataType", curNode );
	}

	public dataTypeType getdataTypeValueAtCursor( org.w3c.dom.Node curNode ) throws Exception {
		if( curNode == null )
			throw new com.altova.xml.XmlException("Out of range");
		else
			return new dataTypeType(getDomNodeValue( dereference(curNode) ) );
	}

	public dataTypeType getdataType() throws Exception 
 {
		return getdataTypeAt(0);
	}

	public void removedataTypeAt(int index) {
		removeDomChildAt(Element, null, "dataType", index);
	}

	public void removedataType() {
		removedataTypeAt(0);
	}

	public void adddataType(dataTypeType value) {
		if( value.isNull() == false )
		{
			appendDomChild(Element, null, "dataType", value.toString());
		}
	}

	public void adddataType(String value) throws Exception {
		adddataType(new dataTypeType(value));
	}

	public void insertdataTypeAt(dataTypeType value, int index) {
		insertDomChildAt(Element, null, "dataType", index, value.toString());
	}

	public void insertdataTypeAt(String value, int index) throws Exception {
		insertdataTypeAt(new dataTypeType(value), index);
	}

	public void replacedataTypeAt(dataTypeType value, int index) {
		replaceDomChildAt(Element, null, "dataType", index, value.toString());
	}

	public void replacedataTypeAt(String value, int index) throws Exception {
		replacedataTypeAt(new dataTypeType(value), index);
	}

	private org.w3c.dom.Node dereference(org.w3c.dom.Node node) {
		return node;
	}
}
