/**
 * dataTypeType.java
 *
 * This file was generated by XMLSpy 2006r3sp1 Enterprise Edition.
 *
 * YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
 * OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
 *
 * Refer to the XMLSpy Documentation for further details.
 * http://www.altova.com/xmlspy
 */


package com.dbconfig;

import com.altova.types.*;

public class dataTypeType extends SchemaString {
	public static String[] sPatternValues = {
		"stringColumn",
		"numberColumn",
	};

	public dataTypeType() {
		super();
	}

	public dataTypeType(String newValue) {
		super(newValue);
		validate();
	}

	public dataTypeType(SchemaString newValue) {
		super(newValue);
		validate();
	}

	public static int getPatternCount() {
		return sPatternValues.length;
	}

	public static String getPatternValue(int index) {
		return sPatternValues[index];
	}

	public void validate() {
	}
}
