/**
 * projectionListType.java
 *
 * This file was generated by XMLSpy 2006r3sp1 Enterprise Edition.
 *
 * YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
 * OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
 *
 * Refer to the XMLSpy Documentation for further details.
 * http://www.altova.com/xmlspy
 */


package com.dbconfig;

import com.altova.types.*;

public class projectionListType extends com.altova.xml.Node {

	public projectionListType(projectionListType node) {
		super(node);
	}

	public projectionListType(org.w3c.dom.Node node) {
		super(node);
	}

	public projectionListType(org.w3c.dom.Document doc) {
		super(doc);
	}

	public projectionListType(com.altova.xml.Document doc, String namespaceURI, String prefix, String name) {
		super(doc, namespaceURI, prefix, name);
	}
	
	public void adjustPrefix() {
		for (	org.w3c.dom.Node tmpNode = getDomFirstChild( Element, null, "projection" );
				tmpNode != null;
				tmpNode = getDomNextChild( Element, null, "projection", tmpNode )
			) {
			internalAdjustPrefix(tmpNode, true);
			new projectionType(tmpNode).adjustPrefix();
		}
	}

	public static int getprojectionMinCount() {
		return 1;
	}

	public static int getprojectionMaxCount() {
		return 1;
	}

	public int getprojectionCount() {
		return getDomChildCount(Element, null, "projection");
	}

	public boolean hasprojection() {
		return hasDomChild(Element, null, "projection");
	}

	public projectionType newprojection() {
		return new projectionType(domNode.getOwnerDocument().createElementNS(null, "projection"));
	}

	public projectionType getprojectionAt(int index) throws Exception {
		return new projectionType(dereference(getDomChildAt(Element, null, "projection", index)));
	}

	public org.w3c.dom.Node getStartingprojectionCursor() throws Exception {
		return getDomFirstChild(Element, null, "projection" );
	}

	public org.w3c.dom.Node getAdvancedprojectionCursor( org.w3c.dom.Node curNode ) throws Exception {
		return getDomNextChild( Element, null, "projection", curNode );
	}

	public projectionType getprojectionValueAtCursor( org.w3c.dom.Node curNode ) throws Exception {
		if( curNode == null )
			throw new com.altova.xml.XmlException("Out of range");
		else
			return new projectionType( dereference(curNode) );
	}

	public projectionType getprojection() throws Exception 
 {
		return getprojectionAt(0);
	}

	public void removeprojectionAt(int index) {
		removeDomChildAt(Element, null, "projection", index);
	}

	public void removeprojection() {
		removeprojectionAt(0);
	}

	public void addprojection(projectionType value) {
		appendDomElement(null, "projection", value);	
	}

	public void insertprojectionAt(projectionType value, int index) {
		insertDomElementAt(null, "projection", index, value);
	}

	public void replaceprojectionAt(projectionType value, int index) {
		replaceDomElementAt(null, "projection", index, value);
	}

	private org.w3c.dom.Node dereference(org.w3c.dom.Node node) {
		return node;
	}
}
